name: ambientes output

on: 
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options: ["dr", "prd", "cer", "dr,prd"]

jobs:
  make-environment:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          if [[ "${{inputs.environment}}" == "dr,prd" ]]; then
            echo "matrix={\"valores\":[\"dr\",\"prd\"]}" >> $GITHUB_OUTPUT
          else
            echo "matrix={\"valores\":[\"${{inputs.environment}}\"]}" >> $GITHUB_OUTPUT
          fi
        shell: bash

  delivery:
    name: Deploy
    needs: make-environment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        valores: ${{fromJson(needs.make-environment.outputs.matrix).valores}}
    environment: ${{ matrix.valores }}
    steps:
      - name: ambiente ${{ matrix.valores }}
        run: echo ${{ matrix.valores }}
