name: Check Inputs Workflow

on:
  workflow_dispatch:
  # workflow_call:
    inputs:
      sonar:
        required: false
        description: 'Whether to use Sonar'
        default: 'false'
        type: string
      fortify:
        required: false
        description: 'Whether to use Fortify'
        default: 'false'
        type: string
      usegates:
        required: false
        description: 'Define quality gate usage'
        default: 'true'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.usegates == 'true' && 'alpine' || 'debian' }}

    steps:
      - name: show
        run: |
          echo ${{ inputs.sonar }}
          echo ${{ inputs.fortify }}
      - name: Run Sonar analysis
        if: ${{ inputs.sonar == 'true' }}
        run: |
          # Commands to run Sonar analysis
          echo "Running Sonar analysis..."

      - name: Run Fortify scan
        if: ${{ inputs.fortify == 'true' }}
        run: |
          # Commands to run Fortify scan
          echo "Running Fortify scan..."

      # Add more steps as needed for your job
