name: Check Inputs Workflow

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      sonar:
        required: false
        description: 'Whether to use Sonar'
        default: 'false'
        type: string
      fortify:
        required: false
        description: 'Whether to use Fortify'
        default: 'false'
        type: string
      usegates:
        required: false
        description: 'defina o gate de qualidade'
        default: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.usegates == 'true' && 'alpine' || 'debian'}}
    
    steps:

      - name: Run Sonar analysis
        if: ${{ inputs.sonar == 'true' }}
        run: |
          # Comandos para executar análise no Sonar
          echo "Running Sonar analysis..."
      
      - name: Run Fortify scan
        if: ${{ inputs.fortify == 'true' }}
        run: |
          # Comandos para executar scan no Fortify
          echo "Running Fortify scan..."
      
      # Adicione mais passos conforme necessário para o seu job
