name: 'runner container'

on:
  workflow_dispatch:

jobs:
  teste:
    runs-on: [self-hosted, brn]
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.7
        
      - name: Run a simple busybox
        uses: docker://busybox
        with:
          entrypoint: /bin/echo
          args: 'Hello from a simple container action!' 
          
      - name: Run a simple alpine action
        uses: docker://alpine:3.12
        with:
          entrypoint: /bin/echo
          args: 'Hello from a simple container action!'
