name: trocando nome de arquivo
on:
  workflow_call:

jobs:
  alteraTexto:
    runs-on: ubuntu-latest

    steps:
      - name: lendo repositorio
        uses: actions/checkout@v4
      - name: imprimindo variavel
        run: echo ${{ vars.NODEPOOL }}
      - name: Set default value if variable is empty
        run: |
          if [ -z "${{ env.NODEPOOL }}" ]; then
            sed -i 's/!!!NODEPOOL!!!/default: ""/g' deployment.txt
          else
            sed -i "s/!!!NODEPOOL!!!/${{ env.NODEPOOL }}/g" deployment.yaml
          fi
        shell: bash
      - name: mostra o arquivo alterado
        run: cat deployment.yaml
