name: teste frontend com robot framework

on:
  workflow_dispatch:


jobs:
  testes-com-robot:
    runs-on: [ubuntu-latest]

    steps:
      - name: faz o checkcout
        uses: actions/checkout@v4

      - name: Inicializa ambiente nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install playwright --save-dev
      - run: npm ci

      - name: Inicializa ambiente python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Configurar cache do rfbrowser
        uses: actions/cache@v4
        with:
          path: /opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/Browser/wrapper
          key: rfbrowser-${{ runner.os }}
          restore-keys: |
            rfbrowser-${{ runner.os }}

      - name: Verificar cache do rfbrowser
        id: cache-rfbrowser-check
        run: |
          # Obter o tamanho do diretório em bytes
          size=$(du -s /opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/Browser/wrapper | awk '{print $1}')
          
          # Definir o tamanho em bytes para 1GB
          size_threshold=1073741824
          
          # Verificar se o tamanho do diretório é maior que 1GB
          if [ "$size" -gt "$size_threshold" ]; then
            echo "cache-found=true" >> "$GITHUB_OUTPUT"
          else
            echo "cache-found=false" >> "$GITHUB_OUTPUT"
          fi


      - name: verifica instala dependencias rfbrowser se necessario
        run: |
          if [ "${{ steps.cache-rfbrowser-check.outputs.cache-found }}" != 'true' ]; then
            rfbrowser init
          fi

      - name: executando testes robot
        run: |
          robot -d ./reports -v HEADLESS:true \
          -v BROWSER:chromium tests

      - name: disponibilizando status dos testes
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports testes no navegador
          path: ./reports
          if-no-files-found: ignore
          retention-days: 1
          overwrite: true

      - name: reports no summary
        uses: joonvena/robotframework-reporter-action@v2
         with:
           gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          
          
          
          
          
