name: teste frontend com robot framework

on:
  workflow_dispatch:


jobs:
  testes-com-robot:
    runs-on: [ubuntu-latest]

    steps:
      - name: faz o checkcout
        uses: actions/checkout@v4

      - name: Inicializa ambiente python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Inicializa ambiente nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'    
