name: Robot Framework Job

on:
  workflow_dispatch:
    

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: brunosoouza/robot

    steps:
    
      - name: List Python Packages
        run: |
          pip list

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BRN }}


      - name: list
        run: ls -alh
