name: Remove Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to remove'
        required: true
        default: 'tag-YYYYMMDDHHMMSS'  # Substitua com a tag padrão ou deixe em branco

jobs:
  remove:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Remove tag
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag -d "${{ github.event.inputs.tag }}"
          git push origin --delete "${{ github.event.inputs.tag }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
