name: teste commit

on: [workflow_dispatch]

jobs:
  teste-commit:
    runs-on: ubuntu-latest
    steps:
      - run: echo "GITHUB_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - run: echo "1" >> increment.txt
      - run: |
      
          git config --global user.email "teste@example.com"
          git config --global user.name "testador"
          git add .
          git commit -m "teste commit"
          git push origin
